
std_id:
  displayName: '{id}'
  uriParameters:
    id:
      description: Object identifier
      type: string
      displayName: Object identifier

std_id_post:
  displayName: '{id}'
  uriParameters:
    id:
      description: Object identifier
      type: string
      displayName: Object identifier
  post:
    is: [stdresponse]
    displayName: update<<resourcePathName | !singularize >>
    description: Update <<resourcePathName | !singularize>> configuration
    body:
      application/json:
        type: <<resourcePathName | !singularize >>

std_id_get_post:
  displayName: '{id}'
  uriParameters:
    id:
      description: Object identifier <<descr>>
      type: string
      displayName: Object identifier

  get:
    is: [stdresponse,authfailure]
    displayName: get<<resourcePathName | !singularize >>
    description: Get <<resourcePathName | !singularize>>, <<descr>>

  post:
    is: [stdresponse,authfailure]
    displayName: update<<resourcePathName | !singularize >>
    description: Update <<resourcePathName | !singularize>>
    body:
      application/json:
        type: <<resourcePathName | !singularize >>

std_id_get_post_del:
  displayName: '{id}'
  uriParameters:
    id:
      description: <<descr>>
      type: string

  get:
    is: [stdresponse,authfailure]
    displayName: get<<resourcePathName | !singularize >>
    description: Get <<resourcePathName | !singularize>>, <<descr>>

  post:
    is: [stdresponse,authfailure]
    displayName: update<<resourcePathName | !singularize >>
    description: Update <<resourcePathName | !singularize>>
    body:
      application/json:
        type: <<resourcePathName | !singularize >>

  delete:
    is: [stdresponse,authfailure]
    displayName: delete<<resourcePathName | !singularize >>
    description: Delete <<resourcePathName | !singularize>>
    body: {}
    responses:
      '200':
        # body:
          # application/json:
          #    type: <<resourcePathName | !singularize >>DeleteStatus
        description: <<resourcePathName | !singularize >> deleted

std_root_list:
  displayName: list<<resourcePathName | !singularize  >>
  get:
    is: [listresponse,authfailure]

std_root_get:
  displayName: get<<resourcePathName | !singularize  >>
  get:
    is: [stdresponse]

std_root_get_id:
  displayName: '{id}'
  uriParameters:
    id:
      description: <<descr>>
      type: string
      displayName: Object identifier

  get:
    is: [listresponse,authfailure]