

#stored on bobj
user:
  type: object
  properties:
    uid:
      required: true
      description: is unique id for a user, increments
      type: number
      format: int32        
    alias:
      required: true
      description: chosen name(s), does not have to be unique, public readable, only relevant in all groups you are part off.
      type: string[]
    key_pub:
      required: false
      description: public key which is used for validation & encryption
      type: string[]
    addr:
      required: false
      description: is the address given by the digital.me system, is unique per user & can change
      type: string
            
  example:
    id: 10    
    addr: "rabbit.luxor.egypt"
    alias:
    - "rabbit"
    - "gouny1"
      
#stored on bobj
group:
  type: object
  properties:
    uid:
      required: true
      description: is unique id for a group, increments
      type: number
      format: int32      
    alias:
      required: true
      description: chosen name(s), does not have to be unique, public readable, only relevant in all parent groups
      type: string[]
    admins:
      required: true
      description: list of admins which are people who administer this group and can add/remove users
      type: number[]
      format: int32
    key_pub:
      required: false
      description: public key which is used for validation & encryption
      type: string[]
    addr:
      required: false
      description: is the address given by the digital.me system, is unique per group & can change
      type: string
  example:
    id: 10    
    addr: "rabbitgroup.luxor.egypt"
    owners: [1,2]
    alias:
    - "gig.engineering"
